#!/bin/bash
# Generates a deterministic test ledger covering all ledger-graphs/v1 scripts.
#
# Outputs to stdout. Typical usage:
#   bash generate_test_data.sh > test.ledger
#
# Data characteristics:
#   - 2 years of monthly bulk transactions (for scripts 2, 3, 5)
#   - Daily transactions for the last 3 months (for script 4)
#   - Known fixed amounts so test assertions can be exact
#   - Special months with edge-case values (bonus, big expense, low month)
#   - Multi-currency: GBP, INR, USD, VUAG (ETF units), GOOG (stock)

set -euo pipefail

if ! command -v dateadd &>/dev/null || ! command -v dateseq &>/dev/null; then
    echo "Requires dateutils: sudo apt install dateutils" >&2
    exit 1
fi

TODAY=$(date +"%Y-%m-%d")
MONTH_START=$(date +"%Y-%m-01")
DAILY_START=$(dateadd "$MONTH_START" -3mo --format="%Y-%m-%d")
MONTHLY_START=$(dateadd "$MONTH_START" -24mo --format="%Y-%m-%d")
BONUS_MONTH=$(dateadd "$MONTH_START" -18mo --format="%Y-%m-01")
HIGH_HEALTH_MONTH=$(dateadd "$MONTH_START" -12mo --format="%Y-%m-01")
BIG_PURCHASE_MONTH=$(dateadd "$MONTH_START" -9mo --format="%Y-%m-01")
LOW_EXPENSE_MONTH=$(dateadd "$MONTH_START" -4mo --format="%Y-%m-01")

income() { local d=$1 account=$2 asset=$3 amt=$4 commodity=$5 desc=$6
    echo "$d * \"$desc\""
    echo "    $asset    $amt $commodity"
    echo "    $account"
    echo ""
}

expense() { local d=$1 account=$2 payee=$3 amt=$4
    echo "$d * \"$payee\""
    echo "    Assets:Bank:HSBC:Savings    -$amt GBP"
    echo "    $account"
    echo ""
}

invest_buy() { local d=$1 asset=$2 units=$3 commodity=$4 cost_gbp=$5 desc=$6
    echo "$d * \"$desc\""
    echo "    $asset    $units $commodity @ $cost_gbp GBP"
    echo "    Assets:Bank:HSBC:Savings    -$(echo "$units * $cost_gbp" | bc) GBP"
    echo ""
}

stock_buy_usd() { local d=$1 asset=$2 shares=$3 commodity=$4 price_usd=$5 desc=$6
    echo "$d * \"$desc\""
    echo "    $asset    $shares $commodity @ $price_usd USD"
    echo "    Assets:Investments:CharlesSchwab:Cash    -$(echo "$shares * $price_usd" | bc) USD"
    echo ""
}

echo "; Generated by tests/generate_test_data.sh on $TODAY"
echo "; Deterministic test data for ledger-graphs/v1 scripts"
echo ""
echo "commodity GBP"
echo "   note Pound Sterling"
echo "   format 1,000.00 GBP"
echo ""
echo "commodity USD"
echo "   note US Dollars"
echo "   format 1,000.00 USD"
echo ""
echo "commodity INR"
echo "   note Indian Rupees"
echo "   format 1,000.00 INR"
echo ""
echo "commodity VUAG"
echo "   note Vanguard FTSE All-World ETF (GBP)"
echo ""
echo "commodity GOOG"
echo "   note Alphabet Inc. (USD)"
echo ""
echo "account Assets:Bank:HSBC:Savings"
echo "account Assets:Bank:SBI:Savings"
echo "account Assets:Investments:CharlesSchwab:Cash"
echo "account Assets:Investments:CharlesSchwab:GOOG"
echo "account Assets:Investments:Fidelity:ISA:VUAG"
echo "account Equity:OpeningBalance"
echo "account Expenses:Allowance"
echo "account Expenses:Entertainment"
echo "account Expenses:Groceries"
echo "account Expenses:Health"
echo "account Expenses:Housing"
echo "account Expenses:Posessions"
echo "account Expenses:Transport"
echo "account Expenses:Utilities"
echo "account Income:Salary"
echo "account Income:SBI:Interest"
echo "account Income:Schwab:Interest"
echo ""

# Opening balances
echo "; ── Opening balances ──────────────────────────────────────────────────────"
echo "$MONTHLY_START * \"Opening Balance\""
echo "    Assets:Bank:HSBC:Savings    10000 GBP"
echo "    Assets:Bank:SBI:Savings     500000 INR"
echo "    Assets:Investments:CharlesSchwab:Cash    5000 USD"
echo "    Equity:OpeningBalance"
echo ""

# ── 2 years of monthly bulk transactions ──────────────────────────────────────
echo "; ── Monthly bulk transactions ─────────────────────────────────────────────"
quarter=0
for cdate in $(dateseq "$MONTHLY_START" 1mo "$DAILY_START"); do
    first="$cdate"
    quarter=$(( (quarter + 1) % 3 ))

    # Standard monthly amounts
    sal=3000
    housing=900
    groceries=350
    utilities=140
    transport=180
    health=40
    allowance=50
    entertainment=50
    posessions=80

    # Special months
    if [[ "$first" == "$BONUS_MONTH" ]]; then
        sal=6500        # annual bonus
    fi
    if [[ "$first" == "$HIGH_HEALTH_MONTH" ]]; then
        health=520      # dental work
    fi
    if [[ "$first" == "$BIG_PURCHASE_MONTH" ]]; then
        posessions=850  # laptop
    fi
    if [[ "$first" == "$LOW_EXPENSE_MONTH" ]]; then
        groceries=80; utilities=90; transport=30
        entertainment=200; posessions=0; allowance=20
    fi

    # GBP salary
    income "$first" "Income:Salary" "Assets:Bank:HSBC:Savings" "$sal" "GBP" "Salary"

    # GBP expenses
    expense "$first" "Expenses:Housing"       "Rent"              "$housing"
    expense "$first" "Expenses:Groceries"     "Supermarket"       "$groceries"
    expense "$first" "Expenses:Utilities"     "Electricity+Gas"   "$utilities"
    expense "$first" "Expenses:Transport"     "Train pass"        "$transport"
    expense "$first" "Expenses:Health"        "Gym"               "$health"
    expense "$first" "Expenses:Allowance"     "Allowance"         "$allowance"
    expense "$first" "Expenses:Entertainment" "Netflix+Spotify"   "$entertainment"
    [[ "${posessions:-0}" -gt 0 ]] && \
    expense "$first" "Expenses:Posessions"    "Online purchase"   "$posessions"

    # INR: SBI savings interest (monthly, ~3% annual on 500000 INR)
    income "$first" "Income:SBI:Interest" "Assets:Bank:SBI:Savings" "1250" "INR" "SBI Savings Interest"

    # USD: Schwab interest (monthly, ~4% annual on 5000 USD)
    income "$first" "Income:Schwab:Interest" "Assets:Investments:CharlesSchwab:Cash" "17" "USD" "Schwab Interest"

    # Quarterly: buy VUAG ETF in Fidelity ISA (months 0, 3, 6 ...)
    if [[ "$quarter" == "0" ]]; then
        invest_buy "$first" "Assets:Investments:Fidelity:ISA:VUAG" "10" "VUAG" "90" "Buy VUAG ETF"
    fi

    # Every 6 months: buy GOOG stock via Schwab
    month_num=$(date -d "$first" +"%m")
    if [[ "$month_num" == "01" || "$month_num" == "07" ]]; then
        stock_buy_usd "$first" "Assets:Investments:CharlesSchwab:GOOG" "1" "GOOG" "175" "Buy GOOG"
    fi
done

# ── Daily transactions for the last 3 months ─────────────────────────────────
echo "; ── Daily transactions (last 3 months) ────────────────────────────────────"
for ddate in $(dateseq "$DAILY_START" 1d "$TODAY"); do
    dom=$(date -d "$ddate" +"%d")
    dow=$(date -d "$ddate" +"%u")   # 1=Mon … 7=Sun

    # 1st of month: rent, utilities, salary
    if [[ "$dom" == "01" ]]; then
        income  "$ddate" "Income:Salary"          "Assets:Bank:HSBC:Savings" 3000 "GBP" "Salary"
        expense "$ddate" "Expenses:Housing"        "Rent"            900
        expense "$ddate" "Expenses:Utilities"      "Electricity+Gas" 140
        income  "$ddate" "Income:SBI:Interest"     "Assets:Bank:SBI:Savings" 1250 "INR" "SBI Savings Interest"
        income  "$ddate" "Income:Schwab:Interest"  "Assets:Investments:CharlesSchwab:Cash" 17 "USD" "Schwab Interest"
    fi

    # Groceries Mon/Wed/Fri/Sat
    if [[ "$dow" == "1" || "$dow" == "3" || "$dow" == "5" || "$dow" == "6" ]]; then
        expense "$ddate" "Expenses:Groceries" "Local shop" 22
    fi

    # Weekday: commute + coffee
    if [[ "$dow" -le "5" ]]; then
        expense "$ddate" "Expenses:Transport" "Tube"   4
        expense "$ddate" "Expenses:Health"    "Coffee" 4
    fi

    # Weekend entertainment
    if [[ "$dow" == "6" || "$dow" == "7" ]]; then
        expense "$ddate" "Expenses:Entertainment" "Restaurant" 35
    fi

    # Mid-month posession purchase
    if [[ "$dom" == "15" ]]; then
        expense "$ddate" "Expenses:Posessions" "Amazon" 45
    fi
done
